### PR TITLE
compilation on Mac OS X; cf. #18

### PR DESCRIPTION
**Pull request by ranocha**
I've added a basic build/compile script for Mac OS X, cf. #18 and #19.

### CODE REVIEW

**Comment by ranocha** [comment]
TODO: This should be tested on another system and the README.md has to be updated.

**Comment by ranocha** [comment]
If you approve these changes, @philipheinisch, we can merge them.

**Comment by philipheinisch** [comment]
It looks good to me, but I can not test it due to hardware issues preventing me from running MacOS. Merge without additional testing.

**Comment by ranocha** [comment]
If there are problems for other users, they can file an issue.

**Pull request merged**
